"""Map2script.py - Converts a map file into a script full of map_tile commands etc"""

import click
import os.path
import dfile.mapdat
import dfile.dinkdat
#TODO: Add options for how the script should be formatted, with procedure name, outpath, and other things like that
@click.command()
@click.argument("path")
@click.argument("outfile")
@click.argument("screennum")
def main(path, outfile, screennum):
    try:
        index = dfile.dinkdat.readindex(os.path.join(path, "dink.dat"))
        mapping = dfile.mapdat.readmap(os.path.join(path, "map.dat"))
    except:
        print("Cannot open MAP.DAT. Check your path and try again")

    mapnum = mapping[(index['screenno'][int(screennum)]) -1]
    mus = index['midi'][int(screennum) - 1]

    with open(outfile, "w") as f:
        #This will make everything ok
        f.write("//AUTOGENERATED. DO NOT MODIFY.\n")
        f.write("void main()\n{\n")
        #Write in tiles
        for i, tiles in enumerate((mapnum['tileno'], mapnum['alt_hard'])):
            if i == 0:
                cmd = "map_tile"
            else:
                cmd = "map_hard_tile"

            for pos, tile in enumerate(tiles):
                f.write("{}({}, {});\n".format(cmd, str(pos+1), str(tile)))

        f.write("draw_background();\n")
        f.write("draw_hard_map();\n")
        if len(mapnum['script']) > 0:
            f.write('external({}, "main");'.format(mapnum['script']))
        if mus > 0:
            f.write("playmidi('{}.mid');".format(mus))
        #f.write("draw_screen();\n")
        #Now draw the sprite
        #TODO: screen script and music
        cmds = {"size" : "sp_size", "brain" : "sp_brain", "speed" : "sp_speed", "basewalk" : "sp_base_walk", "baseidle" : "sp_base_idle", "baseattack" : "sp_base_attack", "basedeath" : "sp_base_die", "delay" : "sp_timing", "depth" : "sp_que", "hitpoints" : "sp_hitpoints", "strength" : "sp_strength", "defense" : "sp_defense", "experience" : "sp_experience", "nohit" : "sp_nohit", "touchdamage" : "sp_touch_damage"}
        for sprite in mapnum['sprites']:
            if sprite['active'] == 1:
                #TODO: All the other sprite properties including clipping
                f.write("int &spr = create_sprite({}, {}, {}, {}, {});\n".format(sprite['x'], sprite['y'], sprite['brain'], sprite['seq'], sprite['frame']))
                if sprite['hardness'] == 1:
                    f.write("sp_hard(&spr, 0);\n")
                if sprite['script']:
                    f.write('sp_script(&spr, "{}");\n'.format(sprite['script']))
                for val in cmds:
                    if sprite[val] != 0:
                        f.write("{}(&spr, {});\n".format(cmds[val], sprite[val]))


        f.write("}")

if __name__ == '__main__':
    main()